apiVersion: v1
kind: Service
metadata:
  name: sbd
  namespace: k8snb
spec:
  type: NodePort
  ports:
  - name: sbd
    port: 8080
    nodePort: 30002
    targetPort: 8080
    protocol: TCP
  selector:
    app: sbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sbd
    spec:
      containers:
        - name: sbd
          image: 192.168.1.127/test/sbd
          ports:
          - containerPort: 8080
          env:
            - name: key
              value: "value"
